# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_explore_ntlights_stac.ipynb.

# %% auto 0
__all__ = ['make_kids_df', 'parse_folder', 'parse_yearmonth', 'transform_kids_df', 'transform_items_df']

# %% ../nbs/04_explore_ntlights_stac.ipynb 5
VIIRS_LINK = 'https://globalnightlight.s3.amazonaws.com/VIIRS_npp_catalog.json'

# %% ../nbs/04_explore_ntlights_stac.ipynb 6
from satstac import Collection, Item
from fastcore.all import *
from urllib.parse import urlparse
from pathlib import Path

import pandas as pd
import re
from shapely.geometry import Polygon, box
import geopandas as gpd

# %% ../nbs/04_explore_ntlights_stac.ipynb 10
def make_kids_df(link=None, rel='child'):
    link = VIIRS_LINK if link is None else link
    col = Collection.open(link)
    links = L(col._data['links'])
    kids = links.filter(lambda o: o['rel'] == rel)
    kids_df = pd.DataFrame.from_records(kids)
    return kids_df

# %% ../nbs/04_explore_ntlights_stac.ipynb 15
def parse_folder(href):
    urlparts = urlparse(href)
    urlpath = Path(urlparts.path)
    return urlpath.parts[1]


# %% ../nbs/04_explore_ntlights_stac.ipynb 17
def parse_yearmonth(folder):
    return folder[4:] if folder.startswith('npp_') else folder

# %% ../nbs/04_explore_ntlights_stac.ipynb 21
def transform_kids_df(kids_df):
    kids_df.drop(columns=['rel','type'], inplace=True)
    kids_df['folder'] = kids_df.href.apply(parse_folder)
    kids_df['baseurl'] = kids_df.href.apply(parse_baseurl) 
    kids_df['yearmonth'] = kids_df.folder.apply(parse_yearmonth)
    return kids_df

# %% ../nbs/04_explore_ntlights_stac.ipynb 35
def transform_items_df(items_df, folder, baseurl):
    items_df.drop(columns=['rel','type'], inplace=True)
    items_df['item_href'] = items_df.href.apply(get_item_href, folder=folder, baseurl=baseurl)
    items_df['stem'] = items_df.href.apply(split_href_type)
    items_df['suffix'] = items_df.href.apply(split_href_type,first=False)
    items_df['base_url'] = baseurl
    items_df['folder'] = folder
    return items_df
