# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntlights-damage-assessment/',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/ntlights-damage-assessment/tree/master/',
                'lib_path': 'ntlights_damage_assessment'},
  'syms': { 'ntlights_damage_assessment.core': { 'ntlights_damage_assessment.core.say_hello': ( 'https://butchland.github.io/ntlights-damage-assessment/core.html#say_hello',
                                                                                                'https://github.com/butchland/ntlights-damage-assessment/tree/master//blob/master/ntlights_damage_assessment/core.py#L7')}}}