# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_build_catalogs.ipynb.

# %% auto 0
__all__ = ['DATA_DB_DIR', 'DB']

# %% ../nbs/02_build_catalogs.ipynb 4
import requests
import json
from fastcore.all import L
import pandas as pd
from typing import Any
from urllib.parse import urlparse
from pathlib import Path
import numpy as np
import re
from shapely.geometry import Polygon, box
import geopandas as gpd
import sqlite3 as sql3
from pandas.io import sql 
import sqlalchemy as sqalc

# %% ../nbs/02_build_catalogs.ipynb 5
from .catalogs import *
from .items import *

# %% ../nbs/02_build_catalogs.ipynb 8
DATA_DB_DIR = '../data/sqlite'
DB = f'{DATA_DB_DIR}/db.db'
