# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_fetch_coords.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_fetch_coords.ipynb 4
import requests
import json
from fastcore.all import L
import pandas as pd
from typing import Any
from urllib.parse import urlparse
from pathlib import Path
import numpy as np
import re
from shapely.geometry import Polygon, box
import geopandas as gpd
import sqlite3 as sql3
from pandas.io import sql 
import sqlalchemy as sqalc

# %% ../nbs/03_fetch_coords.ipynb 5
from ntlights_damage_assessment.build_catalogs import DB
from ntlights_damage_assessment.catalogs import get_data
