# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_items.ipynb.

# %% auto 0
__all__ = ['get_item_href', 'split_href_type', 'transform_items_df']

# %% ../nbs/01_items.ipynb 4
import requests
import json
from fastcore.all import L
import pandas as pd
from typing import Any
from urllib.parse import urlparse
from pathlib import Path
import numpy as np
import re
from shapely.geometry import Polygon, box
import geopandas as gpd

# %% ../nbs/01_items.ipynb 6
from .catalogs import *

# %% ../nbs/01_items.ipynb 12
def get_item_href(href,folder, baseurl):
    return f'{baseurl}/{folder}{href[1:]}'

# %% ../nbs/01_items.ipynb 14
def split_href_type(href, first=True):
    parts = href[2:].split('.')
    return parts[0] if first else '.'.join(parts[1:])
    

# %% ../nbs/01_items.ipynb 15
def transform_items_df(items_df, folder, baseurl):
    items_df.drop(columns=['rel','type'], inplace=True)
    items_df['item_href'] = items_df.href.apply(get_item_href, folder=folder, baseurl=baseurl)
    items_df['stem'] = items_df.href.apply(split_href_type)
    items_df['suffix'] = items_df.href.apply(split_href_type,first=False)
    items_df['base_url'] = baseurl
    items_df['folder'] = folder
    return items_df
